src/main/java/com/algaworks/pedidovenda/model/Usuario.java
package com.algaworks.pedidovenda.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

@Entity
@Table(name = "usuario")
public class Usuario implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String nome;
	private String email;
	private String senha;
	private List<Grupo> grupos = new ArrayList<>();
	
	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	
	@NotBlank
	@Column(nullable = false, length = 80)
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@NotBlank
	@Column(nullable = false, unique = true, length = 255)
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	@NotBlank
	@Column(nullable = false, length = 20)
	public String getSenha() {
		return senha;
	}
	public void setSenha(String senha) {
		this.senha = senha;
	}
	
	@ManyToMany(cascade = CascadeType.ALL)
	@JoinTable(name = "usuario_grupo", joinColumns = @JoinColumn(name="usuario_id"),
			inverseJoinColumns = @JoinColumn(name = "grupo_id"))
	public List<Grupo> getGrupos() {
		return grupos;
	}
	public void setGrupos(List<Grupo> grupos) {
		this.grupos = grupos;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
}

src/main/java/com/algaworks/pedidovenda/controller/CadastroUsuarioBean.java
package com.algaworks.pedidovenda.controller;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.algaworks.pedidovenda.model.Usuario;
import com.algaworks.pedidovenda.service.CadastroUsuarioService;
import com.algaworks.pedidovenda.util.jsf.FacesUtil;

@Named
@ViewScoped
public class CadastroUsuarioBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private CadastroUsuarioService cadastroUsuarioService;
	
	private Usuario usuario; 
		
	public CadastroUsuarioBean() {
		limpar();
	}

	public Usuario getUsuario() {
		return usuario;
	}



	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
 
	

	/*
	public void inicializar() {

		if (FacesUtil.isNotPostback()) {
			categoriasRaizes = categorias.raizes();

			if (this.categoriaPai != null) {
				carregarSubcategorias();
			}
		}
	}*/

	

	public void limpar() {
		usuario = new Usuario();
		
	}

	public void salvar() {

		this.usuario = cadastroUsuarioService.salvar(this.usuario);
		limpar();

		FacesUtil.addInfoMessage("Usuario salvo com sucesso!");
	}

	public boolean isEditando() {
		return this.usuario.getId() != null;
	}
}

src/main/java/com/algaworks/pedidovenda/controller/PesquisaUsuariosBean.java
package com.algaworks.pedidovenda.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.algaworks.pedidovenda.model.Usuario;
import com.algaworks.pedidovenda.repository.Usuarios;
import com.algaworks.pedidovenda.repository.filter.UsuarioFilter;


@Named
@ViewScoped
public class PesquisaUsuariosBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Usuarios usuarios;

	private UsuarioFilter filtro;
	
	private List<Usuario> usuariosFiltrados;
	
	public List<Usuario> getUsuariosFiltrados() {
		return usuariosFiltrados;
	}

	public PesquisaUsuariosBean() {
		filtro = new UsuarioFilter();
	}

	public void pesquisar() {
		usuariosFiltrados = usuarios.filtrados(filtro);
	}

	

	public UsuarioFilter getFiltro() {
		return filtro;
	}

	
}

src/main/webapp/usuarios/CadastroUsuario.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:o="http://omnifaces.org/ui">

    <ui:define name="titulo">#{cadastroUsuarioBean.editando ? 'Edição de usuario' : 'Novo usuario'}</ui:define>
    
    <ui:define name="corpo">
    	<f:metadata>
    		<!-- <o:viewParam name="usuario" value="#{cadastroUsuarioBean.usuario}" />
    		 
    		<f:event listener="#{cadastroUsuarioBean.inicializar}" type="preRenderView" />
			-->
    	</f:metadata>
    
    	<h:form>
	    	<h1>#{cadastroUsuarioBean.editando ? 'Edição de usuario' : 'Novo usuario'}</h1>
	    	
	    	<p:messages autoUpdate="true" closable="true" />
	    	
	    	<p:toolbar style="margin-top: 20px">
	    		<p:toolbarGroup>
	    			<p:button value="Novo" outcome="/usuarios/CadastroUsuario" />
	    			<p:commandButton value="Salvar" id="botaoSalvar"
	    				action="#{cadastroUsuarioBean.salvar}" update="@form" />
	    		</p:toolbarGroup>
	    		<p:toolbarGroup align="right">
	    			<p:button value="Pesquisa" outcome="/usuarios/PesquisaUsuarios" />
	    		</p:toolbarGroup>
	    	</p:toolbar>
	    	
	    	<p:panelGrid columns="2" id="painel" style="width: 100%; margin-top: 20px"
	    		 	columnClasses="rotulo, campo">
	    		
	    		<p:outputLabel value="Nome" for="nome"/>
	    		<p:inputText id="nome" size="60" maxlength="80" value="#{cadastroUsuarioBean.usuario.nome}"/>
	    		
	    		<p:outputLabel value="Email" for="email"/>
	    		<p:inputText id="email" size="60" maxlength="80" value="#{cadastroUsuarioBean.usuario.email}"
	    		validatorMessage="e-Mail inválido">
	    		<f:validateRegex pattern="[a-zA-Z0-9\-\_\.]+@[a-zA-Z0-9\-\_\.]+"/>
	    		</p:inputText>
	    		
	    		
	    		<h:outputText value= "Senha"/>
	    		<p:password id="senha" value="#{cadastroUsuarioBean.usuario.senha}" feedback="true"/>
	    	    		
	    		
	    	</p:panelGrid>
    	</h:form>
    </ui:define>
</ui:composition>

src/main/webapp/usuarios/PesquisaUsuarios.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Pesquisa de usuários</ui:define>

	<ui:define name="corpo">
		<h:form>
			<h1>Pesquisa de usuários</h1>

			<p:messages autoUpdate="true" closable="true" />

			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:commandButton value="Pesquisar"
						action="#{pesquisaUsuariosBean.pesquisar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Novo" outcome="/usuarios/CadastroUsuario" />
				</p:toolbarGroup>
			</p:toolbar>

			<p:panelGrid columns="2" id="painel"
				style="width: 100%; margin-top: 20px" columnClasses="rotulo, campo">

				<p:outputLabel value="Nome" for="nome" />
				<p:inputText id="nome" size="60"
					value="#{pesquisaUsuariosBean.filtro.nome}" />


			</p:panelGrid>

			<p:dataTable id="usuariosTable"
				value="#{pesquisaUsuariosBean.usuariosFiltrados}" var="usuario"
				style="margin-top: 20px" emptyMessage="Nenhum usuario encontrado."
				rows="20" paginator="true" paginatorAlwaysVisible="false"
				paginatorPosition="bottom">

				<p:column headerText="Nome">
					<h:outputText value="#{usuario.nome}" />
				</p:column>

				<p:column headerText="Email">
					<h:outputText value="#{usuario.email}" />
				</p:column>

				<p:column headerText="Senha">
					<h:outputText value="#{usuario.senha}" />
				</p:column>

			</p:dataTable>

			<p:confirmDialog header="Exclusão de usuario"
				message="Tem certeza que deseja excluir o usuario?"
				widgetVar="confirmacaoExclusao">
				<p:button value="Não"
					onclick="confirmacaoExclusao.hide(); return false;" />
				<p:commandButton value="Sim"
					oncomplete="confirmacaoExclusao.hide();" />
			</p:confirmDialog>
		</h:form>
	</ui:define>
</ui:composition>