src/main/java/com/algaworks/pedidovenda/model/ItemPedido.java
package com.algaworks.pedidovenda.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;


@Entity
@Table(name = "item_pedido")
public class ItemPedido implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private Integer quantidade = 1;
	private BigDecimal valorUnitario = BigDecimal.ZERO;
	private Produto produto;
	private Pedido pedido;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(nullable = false, length = 3)
	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor_unitario", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@ManyToOne
	@JoinColumn(name = "produto_id", nullable = false)
	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@ManyToOne
	@JoinColumn(name = "pedido_id", nullable = false)
	public Pedido getPedido() {
		return pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemPedido other = (ItemPedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public BigDecimal getValorTotal() {
		return this.getValorUnitario().multiply(new BigDecimal(this.getQuantidade()));
	}

	@Transient
	public boolean isProdutoAssociado() {
		return this.getProduto() != null && this.getProduto().getId() != null;
	}
	
	@Transient
	public boolean isEstoqueSuficiente() {
		return this.getPedido().isEmitido() || this.getProduto().getId() == null 
			|| this.getProduto().getQuantidadeEstoque() >= this.getQuantidade(); 
	}
	
	@Transient
	public boolean isEstoqueInsuficiente() {
		return !this.isEstoqueSuficiente();
	}
}

src/main/java/com/algaworks/pedidovenda/model/Pedido.java
package com.algaworks.pedidovenda.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "pedido")
public class Pedido implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private Date dataCriacao;
	private String observacao;
	private Date dataEntrega;
	private BigDecimal valorFrete = BigDecimal.ZERO;
	private BigDecimal valorDesconto = BigDecimal.ZERO;
	private BigDecimal valorTotal = BigDecimal.ZERO;
	private StatusPedido status = StatusPedido.ORCAMENTO;
	private FormaPagamento formaPagamento;
	private Usuario vendedor;
	private Cliente cliente;
	private EnderecoEntrega enderecoEntrega;
	private List<ItemPedido> itens = new ArrayList<>();

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", nullable = false)
	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Column(columnDefinition = "text")
	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_entrega", nullable = false)
	public Date getDataEntrega() {
		return dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}

	@NotNull
	@Column(name = "valor_frete", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorFrete() {
		return valorFrete;
	}

	public void setValorFrete(BigDecimal valorFrete) {
		this.valorFrete = valorFrete;
	}

	@NotNull
	@Column(name = "valor_desconto", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorDesconto() {
		return valorDesconto;
	}

	public void setValorDesconto(BigDecimal valorDesconto) {
		this.valorDesconto = valorDesconto;
	}

	@NotNull
	@Column(name = "valor_total", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorTotal() {
		return valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	public StatusPedido getStatus() {
		return status;
	}

	public void setStatus(StatusPedido status) {
		this.status = status;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "forma_pagamento", nullable = false, length = 20)
	public FormaPagamento getFormaPagamento() {
		return formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "vendedor_id", nullable = false)
	public Usuario getVendedor() {
		return vendedor;
	}

	public void setVendedor(Usuario vendedor) {
		this.vendedor = vendedor;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "cliente_id", nullable = false)
	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Embedded
	public EnderecoEntrega getEnderecoEntrega() {
		return enderecoEntrega;
	}

	public void setEnderecoEntrega(EnderecoEntrega enderecoEntrega) {
		this.enderecoEntrega = enderecoEntrega;
	}

	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	public List<ItemPedido> getItens() {
		return itens;
	}

	public void setItens(List<ItemPedido> itens) {
		this.itens = itens;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}
	
	@Transient
	public boolean isExistente() {
		return !isNovo();
	}
	
	@Transient
	public BigDecimal getValorSubtotal() {
		return this.getValorTotal().subtract(this.getValorFrete()).add(this.getValorDesconto());
	}
	
	public void recalcularValorTotal() {
		BigDecimal total = BigDecimal.ZERO;
		
		total = total.add(this.getValorFrete()).subtract(this.getValorDesconto());
		
		for (ItemPedido item : this.getItens()) {
			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}
		}
		
		this.setValorTotal(total);
	}

	public void adicionarItemVazio() {
		if (this.isOrcamento()) {
			Produto produto = new Produto();
			
			ItemPedido item = new ItemPedido();
			item.setProduto(produto);
			item.setPedido(this);
			
			this.getItens().add(0, item);
		}
	}

	@Transient
	public boolean isOrcamento() {
		return StatusPedido.ORCAMENTO.equals(this.getStatus());
	}

	public void removerItemVazio() {
		ItemPedido primeiroItem = this.getItens().get(0);
		
		if (primeiroItem != null && primeiroItem.getProduto().getId() == null) {
			this.getItens().remove(0);
		}
	}

	@Transient
	public boolean isValorTotalNegativo() {
		return this.getValorTotal().compareTo(BigDecimal.ZERO) < 0;
	}

	@Transient
	public boolean isEmitido() {
		return StatusPedido.EMITIDO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoEmissivel() {
		return !this.isEmissivel();
	}

	@Transient
	public boolean isEmissivel() {
		return this.isExistente() && this.isOrcamento();
	}

	@Transient
	public boolean isCancelavel() {
		return this.isExistente() && !this.isCancelado();
	}

	@Transient
	private boolean isCancelado() {
		return StatusPedido.CANCELADO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoCancelavel() {
		return !this.isCancelavel();
	}

	@Transient
	public boolean isAlteravel() {
		return this.isOrcamento();
	}
	
	@Transient
	public boolean isNaoAlteravel() {
		return !this.isAlteravel();
	}
	
	@Transient
	public boolean isNaoEnviavelPorEmail() {
		return this.isNovo() || this.isCancelado();
	}

	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pedido other = (Pedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	
}

src/main/java/com/algaworks/pedidovenda/controller/CadastroPedidoBean.java
package com.algaworks.pedidovenda.controller;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.event.Observes;
import javax.enterprise.inject.Produces;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.lang3.StringUtils;

import com.algaworks.pedidovenda.model.Cliente;
import com.algaworks.pedidovenda.model.EnderecoEntrega;
import com.algaworks.pedidovenda.model.FormaPagamento;
import com.algaworks.pedidovenda.model.ItemPedido;
import com.algaworks.pedidovenda.model.Pedido;
import com.algaworks.pedidovenda.model.Produto;
import com.algaworks.pedidovenda.model.Usuario;
import com.algaworks.pedidovenda.repository.Clientes;
import com.algaworks.pedidovenda.repository.Produtos;
import com.algaworks.pedidovenda.repository.Usuarios;
import com.algaworks.pedidovenda.service.CadastroPedidoService;
import com.algaworks.pedidovenda.util.jsf.FacesUtil;
import com.algaworks.pedidovenda.validation.SKU;

@Named
@ViewScoped
public class CadastroPedidoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Usuarios usuarios;
	
	@Inject
	private Clientes clientes;
	
	@Inject
	private Produtos produtos;
	
	@Inject
	private CadastroPedidoService cadastroPedidoService;
	
	private String sku;

	@Produces
	@PedidoEdicao
	private Pedido pedido;
	
	private List<Usuario> vendedores;
	
	private Produto produtoLinhaEditavel;
	
	public CadastroPedidoBean() {
		limpar();
	}
	
	
	public void inicializar() {
		if (FacesUtil.isNotPostback()) {
			
			
			this.vendedores = this.usuarios.vendedores();
			this.pedido.adicionarItemVazio();
			this.recalcularPedido();
			
		
			System.out.println("método inicializar funcionando corre!!!");
		}
	}
	
	
	
	
	private void limpar() {
		pedido = new Pedido();
		pedido.setEnderecoEntrega(new EnderecoEntrega());
	}
	
	public void pedidoAlterado(@Observes PedidoAlteradoEvent event) {
		this.pedido = event.getPedido();
	}
	
	public void salvar() {
		this.pedido.removerItemVazio();
		
		try {
			this.pedido = this.cadastroPedidoService.salvar(this.pedido);
		
			FacesUtil.addInfoMessage("Pedido salvo com sucesso!");
		} finally {
			this.pedido.adicionarItemVazio();
		}
	}
	
	public void recalcularPedido() {
		if (this.pedido != null) {
			this.pedido.recalcularValorTotal();
		}
	}
	
	public void carregarProdutoPorSku() {
		if (StringUtils.isNotEmpty(this.sku)) {
			this.produtoLinhaEditavel = this.produtos.porSku(this.sku);
			this.carregarProdutoLinhaEditavel();
		}
	}
	
	public void carregarProdutoLinhaEditavel() {
		ItemPedido item = this.pedido.getItens().get(0);
		
		if (this.produtoLinhaEditavel != null) {
			if (this.existeItemComProduto(this.produtoLinhaEditavel)) {
				FacesUtil.addErrorMessage("Já existe um item no pedido com o produto informado.");
			} else {
				item.setProduto(this.produtoLinhaEditavel);
				item.setValorUnitario(this.produtoLinhaEditavel.getValorUnitario());
				
				this.pedido.adicionarItemVazio();
				this.produtoLinhaEditavel = null;
				this.sku = null;
				
				this.pedido.recalcularValorTotal();
			}
		}
	}
	
	private boolean existeItemComProduto(Produto produto) {
		boolean existeItem = false;
		
		for (ItemPedido item : this.getPedido().getItens()) {
			if (produto.equals(item.getProduto())) {
				existeItem = true;
				break;
			}
		}
		
		return existeItem;
	}

	public List<Produto> completarProduto(String nome) {
		return this.produtos.porNome(nome);
	}
	
	public void atualizarQuantidade(ItemPedido item, int linha) {
		if (item.getQuantidade() < 1) {
			if (linha == 0) {
				item.setQuantidade(1);
			} else {
				this.getPedido().getItens().remove(linha);
			}
		}
		
		this.pedido.recalcularValorTotal();
	}
	
	public FormaPagamento[] getFormasPagamento() {
		return FormaPagamento.values();
	}
	
	public List<Cliente> completarCliente(String nome) {
		return this.clientes.porNome(nome);
	}

	public Pedido getPedido() {
		return pedido;
	}
	
	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public List<Usuario> getVendedores() {
		return vendedores;
	}
	
	public boolean isEditando() {
		return this.pedido.getId() != null;
	}

	public Produto getProdutoLinhaEditavel() {
		return produtoLinhaEditavel;
	}

	public void setProdutoLinhaEditavel(Produto produtoLinhaEditavel) {
		this.produtoLinhaEditavel = produtoLinhaEditavel;
	}

	@SKU
	public String getSku() {
		return sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

}

src/main/webapp/WEB-INF/template/pedidos/BotoesPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:toolbar style="margin-top: 20px">
  		<p:toolbarGroup>
  			<p:button value="Novo" outcome="/pedidos/CadastroPedido"/>
  			<p:commandButton value="Salvar" action="#{cadastroPedidoBean.salvar}"
  				update="@form" disabled="#{cadastroPedidoBean.pedido.naoAlteravel}" />
  		</p:toolbarGroup>
  		
  		<p:toolbarGroup align="right">
  			<p:commandButton value="Emitir" action="#{emissaoPedidoBean.emitirPedido }" 
  				process="@form" update="@form" 
  				disabled="#{cadastroPedidoBean.pedido.naoEmissivel or not seguranca.emitirPedidoPermitido}" />
  			<p:commandButton value="Cancelar" action="#{cancelamentoPedidoBean.cancelarPedido }"
  				process="@this" update="@form" 
  				disabled="#{cadastroPedidoBean.pedido.naoCancelavel or not seguranca.cancelarPedidoPermitido}" />
  			<p:commandButton value="Enviar por e-mail" />
  			
  			<p:separator/>
  		
  			<p:button value="Pesquisa" outcome="/pedidos/PesquisaPedidos" />
  		</p:toolbarGroup>
  	</p:toolbar>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/CapaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:panelGrid columns="4" style="width: 100%; margin-top: 20px" columnClasses="rotulo, campo, rotulo, campo">
		<p:outputLabel value="Número" rendered="#{cadastroPedidoBean.pedido.existente}" />
		<h:outputText value="#{cadastroPedidoBean.pedido.id}" rendered="#{cadastroPedidoBean.pedido.existente}" />
		
		<p:outputLabel value="Data de criação" rendered="#{cadastroPedidoBean.pedido.existente}" />
        <h:outputText value="#{cadastroPedidoBean.pedido.dataCriacao}" rendered="#{cadastroPedidoBean.pedido.existente}">
        	<f:convertDateTime pattern="dd/MM/yyyy" />
        </h:outputText>
        
        <p:outputLabel value="Status"/>
        <h:outputText value="#{cadastroPedidoBean.pedido.status.descricao}" />
        
        <p:outputLabel value="Vendedor" for="vendedor"/>
        <p:selectOneMenu id="vendedor" value="#{cadastroPedidoBean.pedido.vendedor}">
            <f:selectItem itemLabel="Selecione" />
            <f:selectItems value="#{cadastroPedidoBean.vendedores}" var="vendedor"
            	itemValue="#{vendedor}" itemLabel="#{vendedor.nome}" />
        </p:selectOneMenu>
        
        <p:outputLabel value="Cliente" for="cliente"/>
        <p:autoComplete id="cliente" size="40" dropdown="true" 
        	value="#{cadastroPedidoBean.pedido.cliente}" completeMethod="#{cadastroPedidoBean.completarCliente}"
        	var="cliente" itemLabel="#{cliente.nome}" itemValue="#{cliente}" forceSelection="true" />
        
        <p:outputLabel value="Forma de pagamento" for="formaPagamento"/>
        <p:selectOneMenu id="formaPagamento" value="#{cadastroPedidoBean.pedido.formaPagamento}">
            <f:selectItem itemLabel="Selecione" />
            <f:selectItems value="#{cadastroPedidoBean.formasPagamento}" var="formaPagamento"
            	itemValue="#{formaPagamento}" itemLabel="#{formaPagamento.descricao}" />
        </p:selectOneMenu>
        
        <p:outputLabel value="Valor do frete" for="valorFrete"/>
        <p:inputText id="valorFrete" size="10" maxlength="10" styleClass="moeda" 
        	value="#{cadastroPedidoBean.pedido.valorFrete}">
        	<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
        	
        	<p:ajax event="change" process="@this" update="totalPedido"
        		listener="#{cadastroPedidoBean.recalcularPedido}" />
        </p:inputText>
        
        <p:outputLabel value="Subtotal" style="font-weight: bold"/>
        <h:outputText value="#{cadastroPedidoBean.pedido.valorSubtotal}" 
        	style="font-weight: bold" id="subtotal">
        	<f:convertNumber type="currency"/>
        </h:outputText>
        
        <p:outputLabel value="Valor de desconto" for="valorDesconto"/>
        <p:inputText id="valorDesconto" size="10" maxlength="10" styleClass="moeda" 
        	value="#{cadastroPedidoBean.pedido.valorDesconto}">
        	<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
        	
        	<p:ajax event="change" process="@this" update="totalPedido"
        		listener="#{cadastroPedidoBean.recalcularPedido}" />
        </p:inputText>
        
        <p:outputLabel value="Total do pedido" style="font-weight: bold; font-size: 1.1em"/>
        <h:outputText value="#{cadastroPedidoBean.pedido.valorTotal}" 
        	style="font-weight: bold; font-size: 1.1em" id="totalPedido">
        	<f:convertNumber type="currency" />
        </h:outputText>
	</p:panelGrid>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/DadosEntregaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    
    
	<p:panelGrid columns="4" style="width: 100%" columnClasses="rotulo, campo, rotulo, campo">
		<p:outputLabel value="Data da entrega" for="dataEntrega" />
		<p:calendar id="dataEntrega" size="10" pattern="dd/MM/yyyy" 
		value="#{cadastroPedidoBean.pedido.dataEntrega}"
		disabled="#{cadastroPedidoBean.pedido.naoAlteravel}"/>
		
		<p:spacer />
		<p:spacer />
	
        <p:outputLabel value="Logradouro" for="entregaLogradouro" />
        <p:inputText id="entregaLogradouro" size="50"
        value="#{cadastroPedidoBean.pedido.enderecoEntrega.logradouro}"
        disabled="#{cadastroPedidoBean.pedido.naoAlteravel}" />

        <p:outputLabel value="Número" for="entregaNumero" />
        <p:inputText id="entregaNumero" size="5"
        value="#{cadastroPedidoBean.pedido.enderecoEntrega.numero}"
        disabled="#{cadastroPedidoBean.pedido.naoAlteravel}" />

        <p:outputLabel value="Complemento" for="entregaComplemento" />
        <p:inputText id="entregaComplemento" size="50" 
        value="#{cadastroPedidoBean.pedido.enderecoEntrega.complemento}"
        disabled="#{cadastroPedidoBean.pedido.naoAlteravel}" />

        <p:outputLabel value="Cidade" for="entregaCidade" />
        <p:inputText id="entregaCidade" size="20" 
        value="#{cadastroPedidoBean.pedido.enderecoEntrega.cidade}"
        disabled="#{cadastroPedidoBean.pedido.naoAlteravel}"/>

        <p:outputLabel value="Estado" for="entregaEstado" />
        <p:inputText id="entregaEstado" size="20"
        value="#{cadastroPedidoBean.pedido.enderecoEntrega.uf}"
        disabled="#{cadastroPedidoBean.pedido.naoAlteravel}" />

        <p:outputLabel value="CEP" for="entregaCep" />
        <p:inputText id="entregaCep" size="10"
        value="#{cadastroPedidoBean.pedido.enderecoEntrega.cep}" 
        disabled="#{cadastroPedidoBean.pedido.naoAlteravel}"/>
	</p:panelGrid>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/ItensPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:dataTable value="#{cadastroPedidoBean.pedido.itens}" var="item" id="tabelaItens">
		<p:column headerText="SKU" style="text-align: center; width: 100px">
			<h:outputText value="#{item.produto.sku}" rendered="#{item.produtoAssociado}"/>
			
			<p:inputText size="8" value="#{cadastroPedidoBean.sku}" label="SKU"
				rendered="#{not item.produtoAssociado}">
				<p:ajax event="change" process="@this" 
					update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal" 
					listener="#{cadastroPedidoBean.carregarProdutoPorSku}" />
			</p:inputText>
		</p:column>
		<p:column headerText="Produto">
			<h:outputText value="#{item.produto.nome}" rendered="#{item.produtoAssociado}" />
		
			<p:autoComplete styleClass="produto-tabela" value="#{cadastroPedidoBean.produtoLinhaEditavel}"
				completeMethod="#{cadastroPedidoBean.completarProduto}"
				var="produto" itemLabel="#{produto.nome}" itemValue="#{produto}" 
				forceSelection="true" rendered="#{not item.produtoAssociado}">
				<p:ajax event="itemSelect" update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal" 
					listener="#{cadastroPedidoBean.carregarProdutoLinhaEditavel}"/>
			</p:autoComplete>
		</p:column>
		<p:column headerText="Valor unitário" style="text-align: right; width: 120px">
			<h:outputText value="#{item.valorUnitario}">
				<f:convertNumber type="currency"/>
			</h:outputText>
		</p:column>
		<p:column headerText="Quantidade" style="text-align: center; width: 100px">
			<p:inputText size="8" value="#{item.quantidade}" />
		</p:column>
		<p:column headerText="Estoque" style="text-align: center; width: 100px">
			<h:outputText value="#{item.produto.quantidadeEstoque}" />
		</p:column>
		<p:column headerText="Valor total" style="text-align: right; width: 100px">
			<h:outputText value="#{item.valorTotal}">
				<f:convertNumber type="currency"/>
			</h:outputText>
		</p:column>
		
		<p:columnGroup type="footer">
			<p:row>
				<p:column colspan="5" footerText="Subtotal" style="text-align: right" />
				<p:column style="text-align: right">
					<f:facet name="footer">
						<h:outputText value="#{cadastroPedidoBean.pedido.valorSubtotal}">
							<f:convertNumber type="currency"/>
						</h:outputText>
					</f:facet>
				</p:column>
			</p:row>
		</p:columnGroup>
	</p:dataTable>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/ObservacaoPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">
		<p:inputTextarea rows="10" style="width: 100%"
			value="#{cadastroPedidoBean.pedido.observacao}" 
			disabled="#{cadastroPedidoBean.pedido.naoAlteravel}"/>
	</h:panelGroup>

</ui:composition>